# Generated by Django 4.2.20 on 2025-09-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(db_column='school_name', max_length=128)),
                ('sex', models.CharField(db_column='sex', max_length=32)),
                ('create_date', models.DateField(db_column='create_date')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=128)),
                ('sex', models.CharField(db_column='sex', max_length=32)),
                ('birth', models.DateField(db_column='birth')),
                ('department', models.CharField(db_column='department', max_length=128)),
                ('address', models.CharField(db_column='address', max_length=128)),
                ('school_id', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='DailyTest.school')),
            ],
        ),
    ]
