# Generated by Django 4.2.20 on 2026-04-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiJobManagement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_status",
                    models.IntegerField(
                        choices=[(0, "待处理"), (1, "处理中"), (2, "已完成")],
                        default=0,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "task_start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务开始时间"
                    ),
                ),
                (
                    "task_complete_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务完成时间"
                    ),
                ),
                (
                    "task_fail_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="任务失败时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_jobs",
                        to="common.doc",
                        verbose_name="关联文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI任务管理",
                "verbose_name_plural": "AI任务管理",
                "db_table": "ai_testcase_jobs",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500, verbose_name="用例标题")),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                ("test_steps", models.TextField(verbose_name="测试步骤")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "很高"),
                            ("P1", "高"),
                            ("P2", "中"),
                            ("P3", "低"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "激活"), ("deleted", "删除")],
                        default="active",
                        max_length=10,
                        verbose_name="用例状态",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "api_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="common.apiinterface",
                        verbose_name="关联接口",
                    ),
                ),
                (
                    "doc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="common.doc",
                        verbose_name="关联文档",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases_by_job",
                        to="AITestCases.aijobmanagement",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "ai_testcase_cases",
                "ordering": ["-created_time"],
            },
        ),
    ]
