# Generated by Django 4.2.20 on 2026-04-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_apidoc_options_alter_doc_options_and_more"),
        ("AITestCases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aijobmanagement",
            name="doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_jobs",
                to="common.commondoc",
                verbose_name="关联文档",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="doc_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="common.commondoc",
                verbose_name="关联文档",
            ),
        ),
        migrations.CreateModel(
            name="ApiInterface",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("api_name", models.CharField(max_length=500, verbose_name="接口名称")),
                (
                    "api_path",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="接口路径"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                            ("PATCH", "PATCH"),
                            ("HEAD", "HEAD"),
                            ("OPTIONS", "OPTIONS"),
                        ],
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                (
                    "request_params",
                    models.TextField(blank=True, null=True, verbose_name="入参"),
                ),
                (
                    "response_params",
                    models.TextField(blank=True, null=True, verbose_name="出参"),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "api_doc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_interfaces",
                        to="common.commondoc",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "API接口",
                "verbose_name_plural": "API接口",
                "ordering": ["-create_time"],
            },
        ),
        migrations.AlterField(
            model_name="testcase",
            name="api_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="AITestCases.apiinterface",
                verbose_name="关联接口",
            ),
        ),
    ]
