# Generated by Django 4.2.20 on 2026-04-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apidoc",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "接口文档（旧）",
                "verbose_name_plural": "接口文档（旧）",
            },
        ),
        migrations.AlterModelOptions(
            name="doc",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "文档（旧）",
                "verbose_name_plural": "文档（旧）",
            },
        ),
        migrations.AlterField(
            model_name="testdata",
            name="api_interface",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_data",
                to="common.apiinterface",
                verbose_name="所属接口",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CommonDoc",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("prd", "PRD文档"), ("api", "API文档")],
                        max_length=10,
                        verbose_name="业务类型",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("doc", "Word文档"),
                            ("docx", "Word文档"),
                            ("xlsx", "Excel文档"),
                            ("xls", "Excel文档"),
                            ("html", "HTML文档"),
                            ("htm", "HTML文档"),
                            ("pdf", "PDF文档"),
                            ("md", "Markdown文档"),
                            ("txt", "文本文档"),
                        ],
                        max_length=10,
                        verbose_name="文件格式",
                    ),
                ),
                ("filename", models.CharField(max_length=500, verbose_name="文件名")),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=50, verbose_name="版本号"
                    ),
                ),
                (
                    "file_content",
                    models.TextField(blank=True, null=True, verbose_name="文件内容"),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="docs/",
                        verbose_name="文件路径",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docs",
                        to="common.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "ordering": ["-create_time"],
                "indexes": [
                    models.Index(
                        fields=["doc_type"], name="common_comm_doc_typ_66b289_idx"
                    ),
                    models.Index(
                        fields=["project", "doc_type"],
                        name="common_comm_project_eb8778_idx",
                    ),
                ],
            },
        ),
    ]
