# Generated by Django 4.2.30 on 2026-04-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_testdata_api_interface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiinterface",
            name="api_doc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_interfaces",
                to="common.commondoc",
                verbose_name="所属文档",
            ),
        ),
    ]
