# Generated by Django 4.2.30 on 2026-05-02 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0004_alter_apiinterface_api_doc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doc",
            name="project",
        ),
        migrations.DeleteModel(
            name="ApiDoc",
        ),
        migrations.DeleteModel(
            name="Doc",
        ),
    ]
