# Generated by Django 4.2.20 on 2025-09-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aitestcase', '0002_alter_project_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='用例标题')),
                ('precondition', models.TextField(blank=True, verbose_name='前置条件')),
                ('test_steps', models.TextField(verbose_name='测试步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('priority', models.CharField(choices=[('P0', '很高'), ('P1', '高'), ('P2', '中'), ('P3', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('active', '激活'), ('deleted', '删除')], default='active', max_length=10, verbose_name='用例状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='aitestcase.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-created_time'],
            },
        ),
    ]
