# Generated by Django 4.2.20 on 2025-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aitestcase', '0003_testcase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_time'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='', max_length=100, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=200, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500, verbose_name='文件名')),
                ('file_content', models.TextField(blank=True, null=True, verbose_name='文件内容')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_case_generated', models.BooleanField(default=False, verbose_name='是否已生成用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='aitestcase.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='doc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='aitestcase.doc', verbose_name='关联文档'),
        ),
    ]
