# Generated by Django 4.2.20 on 2025-11-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aitestcase', '0004_alter_project_options_remove_project_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='doc',
        ),
        migrations.AddField(
            model_name='testcase',
            name='doc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='aitestcase.doc', verbose_name='关联文档'),
        ),
        migrations.CreateModel(
            name='AiJobManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_status', models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已完成')], default=0, verbose_name='任务状态')),
                ('task_start_time', models.DateTimeField(blank=True, null=True, verbose_name='任务开始时间')),
                ('task_complete_time', models.DateTimeField(blank=True, null=True, verbose_name='任务完成时间')),
                ('task_fail_time', models.DateTimeField(blank=True, null=True, verbose_name='任务失败时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='aitestcase.doc', verbose_name='关联文档')),
            ],
            options={
                'verbose_name': 'AI任务管理',
                'verbose_name_plural': 'AI任务管理',
                'db_table': 'ai_job_management',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases_by_job', to='aitestcase.aijobmanagement', verbose_name='关联任务'),
        ),
    ]
