# Generated by Django 4.2.20 on 2026-04-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTestCaseExecution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "case_name",
                    models.CharField(max_length=500, verbose_name="用例名称"),
                ),
                ("base_url", models.CharField(max_length=500, verbose_name="基础URL")),
                ("run_list", models.JSONField(verbose_name="接口执行列表")),
                (
                    "ai_provider",
                    models.CharField(
                        default="zhipu", max_length=20, verbose_name="AI提供商"
                    ),
                ),
                (
                    "precondition",
                    models.TextField(blank=True, null=True, verbose_name="前置条件"),
                ),
                ("testpoint", models.TextField(verbose_name="测试点")),
                ("expectation", models.TextField(verbose_name="预期结果")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "execution_results",
                    models.JSONField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "validation_result",
                    models.JSONField(blank=True, null=True, verbose_name="AI校验结果"),
                ),
                (
                    "total_interfaces",
                    models.IntegerField(default=0, verbose_name="总接口数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功数"),
                ),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                (
                    "total_duration_ms",
                    models.IntegerField(default=0, verbose_name="总耗时(毫秒)"),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "api_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="common.apiinterface",
                        verbose_name="关联接口",
                    ),
                ),
                (
                    "test_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="common.testdata",
                        verbose_name="测试数据",
                    ),
                ),
            ],
            options={
                "verbose_name": "API测试执行记录",
                "verbose_name_plural": "API测试执行记录",
                "db_table": "api_test_case_execution",
                "ordering": ["-create_time"],
            },
        ),
    ]
