# Generated by Django 4.2.30 on 2026-05-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_remove_doc_project_delete_apidoc_delete_doc"),
        ("AITestCases", "0003_fix_api_interface_foreign_key"),
        ("ApiExecution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitestcaseexecution",
            name="test_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="AITestCases.testcase",
                verbose_name="关联测试用例",
            ),
        ),
        migrations.AlterField(
            model_name="apitestcaseexecution",
            name="api_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_executions",
                to="common.apiinterface",
                verbose_name="关联接口",
            ),
        ),
    ]
