# Generated by Django 4.2.20 on 2025-07-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='prdDocs/')),
            ],
        ),
    ]
