# Generated by Django 4.2.20 on 2026-03-02 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aitestcase', '0005_remove_testcase_doc_testcase_doc_id_aijobmanagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500, verbose_name='文件名')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='版本号')),
                ('file_content', models.TextField(blank=True, null=True, verbose_name='文件内容')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='apiDocs/', verbose_name='文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiDocs', to='aitestcase.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '接口文档',
                'verbose_name_plural': '接口文档',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiInterface',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=500, verbose_name='接口名称')),
                ('api_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='接口路径')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, verbose_name='请求方法')),
                ('request_params', models.TextField(blank=True, null=True, verbose_name='入参')),
                ('response_params', models.TextField(blank=True, null=True, verbose_name='出参')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_interfaces', to='aitestcase.apidoc', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': 'API接口',
                'verbose_name_plural': 'API接口',
                'ordering': ['-create_time'],
            },
        ),
    ]
