# Generated by Django 4.2.20 on 2026-03-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aitestcase', '0006_apidoc_apiinterface'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=500, verbose_name='测试数据名称')),
                ('test_data_json', models.JSONField(verbose_name='测试数据JSON')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='aitestcase.apiinterface', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
                'ordering': ['-create_time'],
            },
        ),
    ]
