# Generated by Django 4.2.20 on 2026-04-01 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aitestcase", "0007_testdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdata",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="是否公共参数"),
        ),
        migrations.AlterField(
            model_name="testdata",
            name="api_interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_data",
                to="aitestcase.apiinterface",
                verbose_name="所属接口",
            ),
        ),
    ]
